### ISSUE TITLE
Finds my public IP twice and then crashes

### ISSUE THREAD

**Issue by dnv** [danpilch/aws-dyndns#3]
Found external IP: 88.112.107.181, 88.112.107.181
Updating resource record IP address
Traceback (most recent call last):
  File "C:\Tools\DDNS R53\dns-update.py", line 132, in <module>
    run.update_record()
  File "C:\Tools\DDNS R53\dns-update.py", line 83, in update_record
    'Value': self.external_ip
  File "C:\Users\adm-dnaumov\AppData\Roaming\Python\Python37\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\adm-dnaumov\AppData\Roaming\Python\Python37\site-packages\botocore\client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidChangeBatch: An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: [Invalid Resource Record: FATAL problem: ARRDATANotSingleField (Value contains spaces) encountered with '88.112.107.181, 88.112.107.181']

**Comment by danpilch** [comment]
thanks, this should now be fixed in master
